gene_prot = {'p-CYP115':""">BAC47408.1 blr2143 [Bradyrhizobium diazoefficiens USDA 110]
MADTSGARSNLLHQSVRSIYGDADRFDVTRRHNPHLSFGQGPHFCLGAALARLELGCAFPALFVRLEHLA
LTIAAEDVVYMPSYVIRCPQRLPVTFRPSIA""",'CYP112':""">BAC47409.1 citocromo P-450 BJ-1 [Bradyrhizobium diazoefficiens USDA 110]
MSEQQPLPTLPMWRVDHIEPSPEMLALRANGPIHRVRFPSGHEGWWVTGYDEAKAVLSDAAFRPAGMPPA
AFTPDSVILGSPGWLVSHEGREHARLRAIVAPAFSDRRVKLLVQQVEAIAAHLFETLAAQPQPADLRRHL
SFPLPAMVISALMGVLYEDHAFFAGLSDEVMTHQHESGPRSASRLAWEELRAYIRGKMRDKRQDPDDNLL
TDLLAAVDQGKASEEEAVGLAAGMLVAGHESTVAQIEFGLLAMFRHPQQRERLVGDPSLVDKAVEEILRM
YPPGAGWDGIMRYPRTDVTIAGEHIPAESKVLVGLPATSFDPHHFDDPEIFDIERQEKPHLAFSYGPHAC
IGVALARLELKVVFGSIFQRLPALRLAVAPEQLKLRKEIITGGFEQFPVLW""",'CYP114':""">BAC47410.1 citocromo P-450 BJ-3 [Bradyrhizobium diazoefficiens USDA 110]
MDVQETTAACRDAFAELASPACIHDPYPFMRWLREHDPVHRAASGLFLLSSRHADIFWAFKATGDAFRGPA
PGELARYFSRAATSPSLNLLASTLAMKDPPTHTRLRRLISRDFTMGQIDNLRPSIARIVAARLDGITPAL
ERGEAVDLHREFALALPMLVFAELFGMPQDDMFELAAGIGTILEGLGPHASDPQLAAADAASARVQAYFG
DLIQRKRTDPRRDIVSMLVGAHDDDADTLSDAELISMLWGMLLGGFVTTAASIDHAVLAMLAYPEQRHWL
QADAARVRAFVEEVLRCDAPAMFSSIPRIAQRDIELGGVVIPKNADVRVLIASGNRDPDAFADPDRFDPA
RFYGTSPGMSTDGKIMLSFGHGIHFCLGAQLARVQLAESLPRIQARFPTLAFAGQPTREPSAFLRTFRTL
PVRLHAQGS""",'sdrGA':""">Desidrogenase BAC47411.1 [Bradyrhizobium diazoefficiens USDA 110]
MGRFEGKVAVVTGAGAGIGKACALAIAREGGRVVVADIDGSAAIACTAQIAAEAGHALALAIDIADAQAV
AALFETAERHFGGVDLLVNNASAMHLTPRDRAILELELAVWDQTMATNLRGTLLCCRQAIPRMIARGGGA
IVNMSSCQGLSGDTALTSYAASKAAMNMLSSSLATQYGHAQIRCNAVAPGLIMTERLLAKLDACMQTHLR
RHQLLPRVGRPEDVAALVAFLLSDDAAFITGQVVCIDGGMLAHVPTYADGGNSRAARPAGETAEADAAPR
C""",'CYP117':""">BAC47412.1 citocromo P-450 BJ-4 [Bradyrhizobium diazoefficiens USDA 110]
MDMLLNPLNRRHRLRHDIPVVPGAFPLVGHLPAVVCDLPRLLRRAERTLGSHFWLDFGPAGHLMTSLDPD
ALALLRHKDVSSGLIEDIAPELFGGTLVAQDGIAHRQARDAIQAALLPKGLTLAGIGELFAPVIRARVQR
WRERGDVTILRETGDLMLKLIFSLMGIPAQDLPGWHRKYRQLLQLIVAPPVDLPGLPLRRGRAARDWIDA
RLREFVRAAREHASRTGLINDMVSAFDRSDDALSDDVLVANILLLLGGHDTTASTMAWMVIELARQPGL
WDALVEEAQRVGAVPTRHADLAQCPVAEALFRETLRVHPATPLLVRRALRELRIGQQRIPTGTDLCIPLL
HFSTSALLHEAPDQFRLARWLQRTEPIRPVDMLQFGTGPHFCMGYHLVWLELVQFCIALALTMHEAGVRP
RLLSGVEKGRRYYPTAHPSMTIRIGFS""",'fpps':""">BAC47413.1 farnesil difosfato sintase [Bradyrhizobium diazoefficiens USDA 110]
MNNMQTGSTPHDDRAGVSANGILGAQARGASGRLLPEIWMQDGAKRVEEALARLLCAEDDGETELMAAMR
YATLHGGKRTRALLCLAAGALADTPAHMLDDVGAAIEMMHACTLVHDDLPAMDDDVLRRGLPTVHVKFGE
ATAILVGDALQAHAFLTLASLNAPGDSPIALVRELAQAVSAEGAAGGQAIDLSLVGKHVELDRIVAMHRM
KSGALVRASVRMGALCAVGVNAAHAALYCALDHYSACFGLALQVIDDILDVTADTAALGKTPGKDAAAQK
PTCASIMGLQEARQFALDLLRDAGEAIAPLGPRAERLAQLIQRANAYLFKHAPRA""",'CPS':""">BAC47414.1 blr2149 [Bradyrhizobium diazoefficiens USDA 110]
MRNGWRNSYSGPTRICSNTRHAHERARPHRVAPVPLRSAGGRVHPALCPSPRRRSQRLPAAAHVSANGTS
RVNALSEHILSELRRLLSEMSDGGSVGPSVYDTAQALRFHGNVTGRQDAYAWLIAQQQADGGWGSADFPL
FRHAPTWAALLALQRADPLPGAADAVQTATRFLQRQPDPYAHAVPEDAPIGAELILPQFCGEAASLLGGV
AFPRHPALLPLRQACLVKLGAVAMLPSGHPLLHSWEAWGTSPTTACPDDDGSIGISPAATAAWRAQAVTR
GSTPQVGRADAYLQMASRATRSGIEGVFPNVWPINVFEPCWSLYTLHLAGLFAHPALAEAVRVIVAQLDA
RLGVHGLGPALHFAADADDTAVALCVLHLAGRDPAVDALRHFEIGELFVTFPGERNASVSTNIHALHALR
LLGKPAAGASAYVEANRNPHGLWDNEKWHVSWLYPTAHAVAALAQGKPQWRDERALAALLQAQRDDGGWG
AGRGSTFEETAYALFALHVMDGSEEATGRRRIAQVVARALEWMLARHAAHGLPQTPLWIGKELYCPTRVV
RVAELAGLWLALRWGRRVLAEGAGAAP""",'KS':""">BAC47415.1 blr2150 [Bradyrhizobium diazoefficiens USDA 110]
MIQTERAVQQVLEWGRSLTGFADEHAVEAVRGGQYILQRIHPSLRGTSARTGRDPQDETLIVTFYRELAL
LFWLDDCNDLGLISPEQLAAVEQALGQGVPCALPGFEGCAVLRASLATLAYDRRDYAQLLDDTRCYSAAL
RAGHAQAVAAERWSYAEYLHNGIDSIAYANVFCCLSLLWGLDMATLRARPAFRQVLRLISAIGRLQNDLH
GCDKDRSAGEADNAVILLLQRYPAMPVVEFLNDELAGHTRMLHRVMAEERFPAPWGPLIEAMAAIRVQYY
RTSTSRYRSDAVRGGQRAPA"""} #Aqui foi definido o dicionário com as respectivas chaves e valores. As chaves são o nome dos genes e os valores seu arquivo Fasta com a tradução de aminoácidos respectivas ao gene
        
print(f'O seguinte código foi feito para determinar qual é o arquivo FASTA com os aminoácidos relacionado a um gene e a quantidade de aminoácidos relacionados à esse gene.\nNós temos o mapeamento dos seguintes genes:{gene_prot.keys()}\nPara continuar, escolha o seu gene de interesse:\n') #Esse print é usado para informar o usuário sobre o objetivo do script, as chaves (genes) disponíveis e as intruções.


continuar = True #Define uma variável que será usada para perguntar se o usuário gostaria de continuar procurando ou não

contador = 1 #Usado para printar uma mensagem específica no loop em um momento específico
while continuar == True:
    if contador>1:
        print('Insira outro gene de ineresse:')
    chave = input()
    sequencia = gene_prot[chave]
    texto_fasta = gene_prot[chave]
    partes = texto_fasta.split(']', 1)
    sequencia_pura = partes[1].replace('\n', '')
    qtd_aminoacidos = len(sequencia_pura)
    if chave in gene_prot:
        print('Esse gene possuí',qtd_aminoacidos,'aminoácidos e os aminoácidos que o compõem são:\n', gene_prot[chave])
        print('Gostaria de procurar outro gene? Responda Sim ou Não')
        sim_nao = input()
        if sim_nao == 'Sim':
            continuar = True
            contador += 1
        else:
            continuar = False  #Este loop disponibiliza a capacidade do usuário de inserir qual gene ele quer. Após isso, é retornado o tamanho número de aminoácidos do presentes no gene e qual é o arquiv                                o Fasta respectivo ao gene escolhido. O loop permite ao usuário escolher se quer continuar ou não sua procura, se sim, o loop roda novamente com uma mensagem pedindo para i                                nserir outro gene de interesse, se não, ele fecha o loop e finaliza o código 

